const INITIAL_STATE={simulationRunning:false,simulationTime:"16:00",selected:"INC-015",view:"overview",pending:false,action:"none",feedback:false,metrics:{evidence:0,priority:0,actions:0,feedback:0},incidents:[
{id:"INC-014",loc:"Nuzvid Sector 4",p:"HIGH",score:76,status:"RESCUE STANDBY",people:8,vuln:0,water:1.1,trend:"Stable",wait:9,safety:68,team:"Team B"},
{id:"INC-015",loc:"Nuzvid Sector 7",p:"MEDIUM",score:54,status:"MONITORING",people:4,vuln:1,water:1.2,trend:"Rising",wait:6,safety:76,team:"Unassigned"},
{id:"INC-016",loc:"Nuzvid Sector 5",p:"MEDIUM",score:52,status:"MONITORING",people:5,vuln:0,water:.9,trend:"Stable",wait:7,safety:73,team:"Team C"},
{id:"INC-011",loc:"Nuzvid Sector 2",p:"CRITICAL",score:88,status:"RESCUE IN PROGRESS",people:6,vuln:1,water:1.6,trend:"Rising",wait:14,safety:51,team:"Team A"},
{id:"INC-012",loc:"Nuzvid Sector 9",p:"HIGH",score:71,status:"TEAM EN ROUTE",people:2,vuln:0,water:1,trend:"Rising",wait:11,safety:64,team:"Team D"},
{id:"INC-013",loc:"Nuzvid Sector 3",p:"LOW",score:28,status:"MONITORING",people:2,vuln:0,water:.5,trend:"Stable",wait:2,safety:91,team:"Unassigned"}],
teams:[["Team A","Boat + Water Rescue","INC-011","ACTIVE","08 min"],["Team B","Boat + Medical Support","INC-014","STANDBY","11 min"],["Team C","Ground Rescue","INC-016","ACTIVE","14 min"],["Team D","Medical + Evacuation","INC-012","ACTIVE","09 min"]].map(x=>({id:x[0],cap:x[1],incident:x[2],status:x[3],eta:x[4]})),
routes:[["Route A",82,"2.1 km","11 min","Low"],["Route B",42,"1.4 km","8 min","High"],["Route C",68,"1.9 km","10 min","Moderate"]].map(x=>({id:x[0],score:x[1],distance:x[2],eta:x[3],risk:x[4]})),
shelters:[["Government School Shelter",120,72,"1.8 km","OPEN"],["Community Hall",80,41,"2.4 km","OPEN"],["Primary Health Centre",50,19,"2.9 km","MEDICAL"],["Relief Camp North",160,95,"3.2 km","OPEN"]].map(x=>({name:x[0],capacity:x[1],available:x[2],distance:x[3],status:x[4]})),
evidence:[],risk:0,activity:[{t:"16:00",x:"ResQAI initialized with simulated emergency data."}]};
let state=structuredClone(INITIAL_STATE),resolver=null;
const $=id=>document.getElementById(id),wait=ms=>new Promise(r=>setTimeout(r,ms)),inc=id=>state.incidents.find(i=>i.id===id);
function time(t){state.simulationTime=t;$("simulation-time").textContent="SIM "+t}
function act(x){state.activity.unshift({t:state.simulationTime,x});renderActivity()}
function evidence(title,x){state.evidence.unshift({t:state.simulationTime,title,x});state.metrics.evidence++;renderEvidence()}
function toast(a,b){let d=document.createElement("div");d.className="toast";d.innerHTML="<b>"+a+"</b><span>"+b+"</span>";$("toast-container").appendChild(d);setTimeout(()=>d.remove(),3500)}
function priority(i){let s=30+Math.min(25,i.vuln*20)+Math.min(20,i.water*9)+(i.trend==="Rising"?15:0)+Math.max(0,10-i.safety/10)+Math.min(10,i.wait/3);s=Math.round(Math.min(100,s));return{s,p:s>=85?"CRITICAL":s>=65?"HIGH":s>=40?"MEDIUM":"LOW"}}
function recalc(){let i=inc("INC-015"),old=i.p,r=priority(i);i.score=r.s;i.p=r.p;if(old!==i.p){state.metrics.priority++;act("INC-015 priority changed "+old+" → "+i.p);toast("PRIORITY CHANGED","INC-015: "+old+" → "+i.p)}renderAll()}
function setView(v){state.view=v;document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));$("view-"+v).classList.add("active");document.querySelectorAll("[data-nav]").forEach(x=>x.classList.toggle("active",x.dataset.nav===v));let n={overview:"Operational Overview",incidents:"Live Incidents",risk:"Risk Intelligence",resources:"Rescue Resources",routes:"Route Intelligence",shelters:"Safe Locations",evidence:"Evidence Timeline",analytics:"Operational Analytics"};$("page-title").textContent=n[v];renderAll()}
function waitOperator(){return new Promise(r=>{resolver=r;$("operator-wait-banner").classList.remove("hidden");setView("overview")})}
function approve(){let a=inc("INC-014"),b=inc("INC-015"),t=state.teams.find(x=>x.id==="Team B");a.team="Unassigned";a.status="MONITORING";b.team="Team B";b.status="RESCUE IN PROGRESS";b.safety=68;t.incident="INC-015";t.status="DEPLOYED";state.pending=false;state.action="approved";state.metrics.actions++;act("Reallocation approved by operator — Team B → INC-015");evidence("Operator decision","Human operator approved Team B reallocation.");toast("OPERATOR APPROVED","Team B dispatched to INC-015.");$("reallocation-panel").classList.add("hidden");$("operator-wait-banner").classList.add("hidden");renderAll();if(resolver){resolver("approved");resolver=null}}
function reject(){state.pending=false;state.action="rejected";state.metrics.actions++;act("Operator rejected the AI reallocation recommendation");toast("RECOMMENDATION REJECTED","Existing allocation retained.");$("reallocation-panel").classList.add("hidden");$("operator-wait-banner").classList.add("hidden");renderAll();if(resolver){resolver("rejected");resolver=null}}
function reset(){state=structuredClone(INITIAL_STATE);resolver=null;$("priority-alert").classList.add("hidden");$("reallocation-panel").classList.add("hidden");$("operator-wait-banner").classList.add("hidden");renderAll();setView("overview")}
async function run(){
 if(state.simulationRunning)return;reset();state.simulationRunning=true;$("btn-run-simulation").disabled=true;$("btn-run-simulation").textContent="● SIMULATION RUNNING";
 try{
 await wait(800);time("16:02");$("location-status").textContent="Incoming SMS received — extracting location…";evidence("Incoming SMS","Rising water near Sector 7; wheelchair user reported.");act("Incoming citizen report entered evidence intake.");toast("INCOMING SMS","Water rising near Sector 7; vulnerable resident reported.");
 await wait(800);time("16:03");$("location-status").textContent="Location detected: Nuzvid Sector 7 · Simulated confidence 94%";evidence("Automatic location detection","Nuzvid Sector 7 matched from simulated report metadata.");act("Automatic location detection matched Nuzvid Sector 7.");
 await wait(800);time("16:04");inc("INC-015").status="ASSESSMENT";evidence("Incident created","INC-015 created from incoming report.");act("Incident created from incoming report.");
 await wait(800);time("16:05");let i=inc("INC-015");i.water=1.5;i.wait=12;i.safety=58;i.trend="Rising";state.risk=1;evidence("Water level update","Water level increased from 1.2 m to 1.5 m.");act("Water evidence strengthened; risk trajectory updated.");renderAll();
 await wait(800);time("16:06");i.water=1.8;i.wait=18;i.safety=42;i.vuln=1;state.risk=3;evidence("Risk evidence update","Water reached 1.8 m; waiting time 18 min; route safety deteriorating.");act("Route safety dropped to 42/100.");renderAll();
 await wait(800);time("16:07");i.score=90;i.p="CRITICAL";state.metrics.priority++;evidence("Priority engine","Combined evidence produces simulated critical score 90/100.");act("INC-015 changed MEDIUM → CRITICAL.");$("priority-alert").classList.remove("hidden");renderAll();
 await wait(800);time("16:08");state.pending=true;$("reallocation-panel").classList.remove("hidden");act("AI recommends reallocating Team B from INC-014 → INC-015");renderAll();
 let d=await waitOperator();
 if(d==="approved"){await wait(800);time("16:11");state.routes[0].score=68;evidence("Route recalculation","Route A changed 82 → 68; Route C recommended.");act("Route C recommended after safety recalculation.");renderAll();await wait(800);time("16:13");i.water=2;i.safety=61;state.metrics.feedback++;evidence("Field team feedback","Water depth higher than initial estimate.");act("Team B feedback received; evidence and route state updated.");toast("FIELD FEEDBACK","Operational picture recalculated.");recalc();await wait(800);time("16:15");evidence("Closed-loop update","Field feedback propagated into evidence, risk, route and priority state.");act("ResQAI recalculated the operational picture after field feedback.");await wait(800);time("16:16");i.status="RESCUE IN PROGRESS";$("footer-state").textContent="RESQAI CONTINUES MONITORING";toast("RESCUE IN PROGRESS","INC-015 remains under continuous monitoring.");renderAll()}
 }finally{state.simulationRunning=false;$("btn-run-simulation").disabled=false;$("btn-run-simulation").textContent="▶ RUN EMERGENCY SIMULATION";$("operator-wait-banner").classList.add("hidden");renderAll()}
}
function renderKpi(){$("kpi-active").textContent=String(state.incidents.length).padStart(2,"0");$("kpi-critical").textContent=String(state.incidents.filter(i=>i.p==="CRITICAL").length).padStart(2,"0");$("kpi-people").textContent=state.incidents.reduce((a,i)=>a+i.people,0)}
function renderIncident(){let i=inc(state.selected)||inc("INC-015");$("selected-title").textContent=i.id+" · "+i.loc;$("selected-priority").className="badge "+i.p.toLowerCase();$("selected-priority").textContent=i.p;$("incident-panel").innerHTML='<div class="incident-details"><div class="detail"><span>AFFECTED PEOPLE</span><b>'+i.people+'</b></div><div class="detail"><span>VULNERABLE</span><b>'+i.vuln+'</b></div><div class="detail"><span>WATER DEPTH</span><b>'+i.water.toFixed(1)+' m</b></div><div class="detail"><span>TREND</span><b>'+i.trend+'</b></div><div class="detail"><span>WAITING</span><b>'+i.wait+' min</b></div><div class="detail"><span>ROUTE SAFETY</span><b>'+i.safety+'/100</b></div><div class="detail wide"><span>STATUS</span><b>'+i.status+'</b></div><div class="detail wide"><span>ASSIGNED RESOURCE</span><b>'+i.team+'</b></div></div>'}
function renderMap(){let s=$("map-svg");s.innerHTML='<defs><pattern id="g" width="45" height="45" patternUnits="userSpaceOnUse"><path d="M45 0H0V45" stroke="#16334b" fill="none"/></pattern></defs><rect width="760" height="390" fill="url(#g)"/><path d="M0 330C130 285 240 360 370 315S610 290 760 330V390H0Z" class="mapwater"/><path d="M20 300C150 215 250 280 370 180S580 90 735 130M60 55C170 105 220 85 305 130S500 245 690 205" class="maproad"/>';state.incidents.forEach((i,n)=>{let x=90+(n%3)*280,y=80+Math.floor(n/3)*180;s.innerHTML+='<circle class="mapdot '+i.p.toLowerCase()+'" cx="'+x+'" cy="'+y+'" r="'+(i.id==="INC-015"?13:9)+'" data-id="'+i.id+'"/><text class="maplabel" x="'+(x+15)+'" y="'+(y+4)+'">'+i.id+'</text>'});s.querySelectorAll("[data-id]").forEach(x=>x.onclick=()=>{state.selected=x.dataset.id;renderIncident()})}
function renderActivity(){$("activity-log").innerHTML=state.activity.slice(0,8).map(a=>'<div class="activity"><time>'+a.t+'</time>'+a.x+'</div>').join("")}
function renderEvidence(){$("evidence-timeline").innerHTML=state.evidence.length?state.evidence.map(e=>'<div class="event"><time>'+e.t+'</time><b>'+e.title+'</b><p>'+e.x+'</p></div>').join(""):'<div class="event"><time>—</time><b>No new evidence</b><p>Run the simulation to populate the evidence chain.</p></div>'}
function renderRisk(){let labels=["Moderate","Elevated","High","Critical"];$("risk-evolution").innerHTML=labels.map((x,n)=>'<div class="stage '+(n===state.risk?'current':n<state.risk?'done':'')+'"><small>STAGE '+(n+1)+'</small><b>'+x+'</b></div>').join("");let i=inc("INC-015"),f=[["Vulnerability",i.vuln?91:40],["Water severity",Math.min(100,Math.round(i.water/2*100))],["Rate of rise",i.trend==="Rising"?88:35],["Waiting time",Math.min(100,i.wait*4)],["Route risk",100-i.safety]];$("priority-factors").innerHTML=f.map(x=>'<div class="factor"><div class="factor-top"><span>'+x[0]+'</span><b>'+x[1]+'</b></div><div class="bar"><i style="width:'+x[1]+'%"></i></div></div>').join("")}
function renderLists(){$("incident-list").innerHTML=state.incidents.map(i=>'<article class="incident-card" data-inc="'+i.id+'"><span class="eyebrow">'+i.id+'</span><span class="badge '+i.p.toLowerCase()+'" style="float:right">'+i.p+'</span><h3>'+i.loc+'</h3><p class="muted">'+i.status+' · '+i.team+'</p><div class="mini">People <b>'+i.people+'</b> Water <b>'+i.water.toFixed(1)+'m</b> Safety <b>'+i.safety+'</b></div></article>').join("");document.querySelectorAll("[data-inc]").forEach(x=>x.onclick=()=>{state.selected=x.dataset.inc;setView("overview")});$("resource-list").innerHTML=state.teams.map(t=>'<article class="resource-card"><span class="eyebrow">'+t.id+'</span><h3>'+t.cap+'</h3><p class="muted">'+(t.incident?"Assigned to "+t.incident:"Available")+'</p><div class="mini"><b>'+t.status+'</b> ETA <b>'+t.eta+'</b></div></article>').join("");$("route-list").innerHTML=state.routes.map(r=>'<article class="route-card"><span class="eyebrow">'+r.id+'</span><h3>'+r.risk+' risk · '+r.eta+'</h3><div class="score '+(r.score<50?"bad":"good")+'">'+r.score+'<small>/100</small></div><p class="muted">'+r.distance+' · INC-015</p><div class="routebar"><i style="width:'+r.score+'%"></i></div></article>').join("");$("shelter-list").innerHTML=state.shelters.map(s=>'<article class="resource-card"><span class="eyebrow">'+s.status+'</span><h3>'+s.name+'</h3><p class="muted">'+s.distance+' · capacity '+s.capacity+'</p><div class="mini"><b>'+s.available+' available</b> '+Math.round(s.available/s.capacity*100)+'% remaining</div></article>').join("")}
function renderAll(){renderKpi();renderIncident();renderMap();renderActivity();renderEvidence();renderRisk();renderLists();$("analytics-evidence").textContent=state.metrics.evidence;$("analytics-priority").textContent=state.metrics.priority;$("analytics-actions").textContent=state.metrics.actions;$("analytics-feedback").textContent=state.metrics.feedback;if(state.pending)$("reallocation-panel").classList.remove("hidden");$("footer-state").textContent=state.feedback?"RESQAI CONTINUES MONITORING":"RESQAI READY FOR SIMULATION"}
document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll("[data-nav]").forEach(x=>x.onclick=()=>setView(x.dataset.nav));$("btn-run-simulation").onclick=run;$("btn-reset-simulation").onclick=reset;$("btn-approve-reallocation").onclick=approve;$("btn-reject-reallocation").onclick=reject;$("btn-review-reallocation").onclick=()=>toast("OPERATOR REVIEW","Team B → INC-015 recommendation is awaiting your decision.");renderAll()});